site_name: XiCorPy
repo_url: https://github.com/swarnakumar/xicorpy

theme:
  name: "material"

markdown_extensions:
  - footnotes

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - xicorpy

nav:
  - Home: index.md
  - Chatterjee's Xi: xi.md
  - Conditional Dependence: codec.md
  - FOCI: foci.md
  - API Reference:
      - XiCor: xicor_api.md
      - Conditional Dependence: codec_api.md
      - FOCI: foci_api.md
