[tool.poetry]
name = "xicorpy"
version = "0.1.0"
description = "Python implementation of Chatterjee's Rank Correlation, its modifications, and other offshoots"
authors = ["Swarna Vallabhaneni <swarnakumar@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9,<3.11"
pandas = "^1.3.5"
numpy = "^1.22.0"
scipy = "^1.7.3"
mypy = "0.931"
mkdocstrings = "^0.17.0"
mkdocs-material = "^8.1.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pre-commit = "^2.16.0"
coverage = {extras = ["toml"], version = "^6.2"}
mypy = "^0.931"
ipython = "^7.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--cov="

[tool.coverage.run]
omit = [".*", "*/site-packages/*"]
source = ["src"]

[tool.coverage.report]
fail_under = 100
